### ISSUE TITLE
Unwanted characters in raw post data

### ISSUE THREAD

**Issue by simoheinonen** [jsargiot/restman#12]
When sending raw POST data there's always 2 extra characters in every request. This is really annoying when in the server side we calculate the hash of the content and it doesn't match to what we want because of those extra characters.

The easiest way to reproduce this is to send empty raw post data request and you'll see Content-Length is 2 and these two characters are being sent:

```
&#13;&#10;
```

The problem is this line:
https://github.com/jsargiot/restman/blob/master/restman/js/ui/request.js#L40-40

Looks like an easy fix but not sure why it was done like that in the first place? Why do we replace new lines with windows new lines and why do we add an extra one?

**Comment by jsargiot** [comment]
Thanks for the report, I'll dig a bit into this... I remember adding that extra line ending and the replace to overcome some bug in the editor itself, which it might have been fixed...
