### ISSUE TITLE
Display HTML response as HTML

### ISSUE THREAD

**Issue by udivankin** [jsargiot/restman#14]
In some not-so-production-ready rest API`s there could be heavy-styled error responses (like Xdebug or Whoops does), it's a pain to dig in their markup to find out error message. Is it possible to have HTML ResponseContent ?

**Comment by jsargiot** [comment]
Sure, I know what you mean, I'll add it in the next version.

**Comment by udivankin** [comment]
Great!
I've made pull request with this functionality, hope it helps.

**Comment by jsargiot** [comment]
Thanks @udivanking. It's going to be included in v0.5 (to be released soon).
