### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by dbautistav** [jsargiot/restman#16]
**A dark theme for those of us who work at night.**

For common pages I use [DarkReader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en), but this can't be used at extension pages. A dark theme could do the job.

**Comment by jsargiot** [comment]
Thanks @dbautistav for the report I'll take a look at darkreader and see what the extension would look like and create a dark theme. If you have examples of dark themes that you consider good please share them! :smile:

**Comment by dbautistav** [comment]
Hey @jsargiot!

![dark-restman-00](https://cloud.githubusercontent.com/assets/8743976/12690121/ed204f62-c6a6-11e5-8637-cfded5bb73c9.png)

![dark-restman-01](https://cloud.githubusercontent.com/assets/8743976/12690122/efebd036-c6a6-11e5-9701-5a227aaaf714.png)

Based on these screenshots, here are some suggestions:
- The blue-ish parts (top and bottom frames, some labels) when in dark theme could be something like: `#89696A`.
- The most light parts (like the main status bar status, time, size, type), when dark: `#1B1B1A`.
- The "Headers"/"Body"/"Response" frames when dark: `#1F1F1E`.
- Text color on dark background: `#CDCAC5`.
- Red buttons when dark theme: `#DAAEA9`.

Those colors were "extracted" from screenshots with Gpick. Someone with better color theory knowledge than mine could easily improve the theme.

**Comment by jsargiot** [comment]
Dark theme has been added to restman on commit 79b87cc.
