### ISSUE TITLE
(feature request) save query

### ISSUE THREAD

**Issue by altsheets** [jsargiot/restman#21]
Hi Joaquin,
great tool, it is working well! Kudos.

I have quite complex queries, with a lot of headers, etc. 
Now each time I re-start working on them, I have to fill in all the fields anew.

Please consider a "save query" option. 

Into the browser memory?

OR, even better, then the queries can be shared among people:
Take all the inputs, and once I press the "execute" button, it redirects to a new page, where all my inputs are urlencoded, and attached to a RESTMAN url, like:

`chrome-extension://aahelpfcopefplnmnphdochceilphfeb/index.html?headers=content-type|application/json&method=post&url=https://api....&....`

Then I could store that url manually, and even send it to other users of RESTMAN.

What do you think?

Sunny greetings to Argentina!

**Comment by jsargiot** [comment]
Hey! That's a great feature!! 

> Now each time I re-start working on them, I have to fill in all the fields anew.
> Please consider a "save query" option.

When you say you have to fill in all the fields, how is this different from clicking on the history item? I mean if you have made the request before it should load all the details of the request.

The "share request" is certainly interesting!

Right now I can't commit to a date but I'll work on this as soon as possible! :)

Thanks for your feedback!!
