### ISSUE TITLE
Method drop down menu issues in Dark Theme

### ISSUE THREAD

**Issue by raworre** [jsargiot/restman#23]
When dark theme is selected the options in the method drop down menu become invisible unless hovered over.

![image](https://user-images.githubusercontent.com/5312355/28024157-83720c6e-6555-11e7-87a6-2df626075f06.png)

**Comment by jsargiot** [comment]
Hi! Thanks for the report, so I see you are using chrome, can you tell me which version? I'll try to fix it and release a new version with some other minor fixes in the coming week

**Comment by raworre** [comment]
@jsargiot This is Chrome 59.0.3071.115 (64-bit) and RestMan 0.6
