### ISSUE TITLE
Removed from Chrome Web Store

### ISSUE THREAD

**Issue by samschurter** [jsargiot/restman#31]
I know it's technically an Opera extension, but it WAS published in the Chrome Web Store and it worked very well in Chrome, I've been using it for years. 

However, as of a few days ago, the page for the web store returns a 404: https://chrome.google.com/webstore/detail/restman/ihgpcfpkpmdcghlnaofdmjkoemnlijdi

And according to Chrome Stats it was removed 6-10-22: 
https://chrome-stats.com/d/ihgpcfpkpmdcghlnaofdmjkoemnlijdi/download

Any reason it was removed? I recommend this extension to coworkers all the time since it's faster than Postman for simple stuff

**Comment by alandillon** [comment]
Edge told me it was marked as Malware

**Comment by jsargiot** [comment]
Sorry guys, the extension was removed from the Chrome Web Store (it seems not having an icon it's enough to get you delisted :shrug: ), I'm sorting out the details, will let you know once it's fixed.

**Comment by jsargiot** [comment]
It's back, please let me know if you still face issues. Thanks for reporting!
