### ISSUE TITLE
feature request: JSON prettyprint

### ISSUE THREAD

**Issue by altsheets** [jsargiot/restman#9]
Taking this http://api.nhzcrypto.org:7776/nhz?requestType=getAsset&asset=8101260088962758269 as an example ...

... what about formatting the response body with some pprint function?

At the moment it is only one looooong line, not very useful for my purposes.

Thanks!

**Comment by altsheets** [comment]
Or ... to which other restclient plugin for Opera29 could you point me? Thanks.

**Comment by jsargiot** [comment]
Please check the recently published 0.3 version, the JSON button on the response text box should also prettify the code (if it's valid).

Running that url on RestMan v0.3 I see that the Content-Type returned by the server is text/plain, so it will be treated as simple text, click on the JSON button on the right lower corner, it should be formatted.

**Comment by altsheets** [comment]
Thanks for your quick answer! Much appreciated.

It does colour it, yes. But what about newlines after each tuple?

Have a look how it is solved in this one: http://restforchrome.blogspot.de/

**Comment by altsheets** [comment]
I suggest you put the version number somewhere visible, or create an "about" menu ...

... took me a moment to realize that I was not in the newest version.

**Comment by altsheets** [comment]
But anyways ... many thanks. 
Now it is exactly what I had hoped for!
Good luck to your.

**Comment by jsargiot** [comment]
Thanks for the feedback! I'll add the version in the next release! :+1:
